data_root:
  '9': '/data3/finance'

dataset_setting:
  'vol': 
    time_idx: 'days_from_start'
    target: 'log_vol'
    group_ids: ['Region', 'Symbol']
    static_categoricals: ['Region', 'Symbol']
    static_reals: []
    time_varying_known_categoricals: ["day_of_week", "day_of_month", "week_of_year", "month"]
    variable_groups: {}
    time_varying_known_reals: ["days_from_start"]
    time_varying_unknown_categoricals: []
    time_varying_unknown_reals: ["log_vol", "open_to_close"]

  'stock_idx': 
    time_idx: 'days_from_start'
    target: 'close_price'
    group_ids: ['Region', 'Symbol']
    static_categoricals: ['Region', 'Symbol']
    static_reals: []
    time_varying_known_categoricals: ["day_of_week", "day_of_month", "week_of_year", "month"]
    variable_groups: {}
    time_varying_known_reals: ["days_from_start"]
    time_varying_unknown_categoricals: []
    time_varying_unknown_reals: ["close_price", "log_vol", "open_to_close"]
    
  'btc_krw': 
    time_idx: 'days_from_start'
    target: 'Close'
    group_ids: ['Symbol']
    static_categoricals: ['Symbol']
    static_reals: []
    time_varying_known_categoricals: ['day_of_week', 'day_of_month', 'week_of_year', 'month']
    variable_groups: {}
    time_varying_known_reals: ["days_from_start"]
    time_varying_unknown_categoricals: []
    time_varying_unknown_reals: ["Close", "Volume", "Change"]

  'btc_usd': 
    time_idx: 'days_from_start'
    target: 'Close'
    group_ids: ['Symbol']
    static_categoricals: ['Symbol']
    static_reals: []
    time_varying_known_categoricals: ['day_of_week', 'day_of_month', 'week_of_year', 'month']
    variable_groups: {}
    time_varying_known_reals: ["days_from_start"]
    time_varying_unknown_categoricals: []
    time_varying_unknown_reals: ["Close", "Volume", "Change"]

  'crypto': 
    time_idx: 'days_from_start'
    target: 'Close'
    # target: 'Return'
    group_ids: ['Symbol']
    static_categoricals: ['Symbol']
    static_reals: []
    time_varying_known_categoricals: ['day_of_week', 'day_of_month', 'week_of_year', 'month']
    variable_groups: {}
    time_varying_known_reals: ["days_from_start"]
    time_varying_unknown_categoricals: []
    time_varying_unknown_reals: ["Return", "Close", "Volume", "Market Cap"]
    # time_varying_unknown_reals: ["Return"]

  'crypto_hourly': 
    time_idx: 'hours_from_start'
    target: 'Close'
    group_ids: ['Symbol']
    static_categoricals: ['Symbol']
    static_reals: []
    time_varying_known_categoricals: ['hour', 'day_of_week', 'day_of_month', 'week_of_year', 'month']
    variable_groups: {}
    time_varying_known_reals: ["hours_from_start"]
    time_varying_unknown_categoricals: []
    time_varying_unknown_reals: ["Return", "Close", "Volume USD"]

  'crypto_daily': 
    time_idx: 'days_from_start'
    target: 'Close'
    group_ids: ['Symbol']
    static_categoricals: ['Symbol']
    static_reals: []
    time_varying_known_categoricals: ['day_of_week', 'day_of_month', 'week_of_year', 'month']
    variable_groups: {}
    time_varying_known_reals: ["days_from_start"]
    time_varying_unknown_categoricals: []
    time_varying_unknown_reals: ["Return", "Close", "Volume USD"]

  'sp500': 
    time_idx: 'days_from_start'
    target: 'Close'
    group_ids: ['Symbol']
    static_categoricals: ['Symbol', 'Sector']
    static_reals: []
    time_varying_known_categoricals: ['day_of_week', 'day_of_month', 'week_of_year', 'month']
    variable_groups: {}
    time_varying_known_reals: ["days_from_start"]
    time_varying_unknown_categoricals: []
    time_varying_unknown_reals: ["Close", "Volume"]

  'kospi': 
    time_idx: 'days_from_start'
    target: 'Close'
    group_ids: ['Symbol']
    static_categoricals: ['Symbol', 'Sector']
    static_reals: []
    time_varying_known_categoricals: ['day_of_week', 'day_of_month', 'week_of_year', 'month']
    variable_groups: {}
    time_varying_known_reals: ["days_from_start"]
    time_varying_unknown_categoricals: []
    time_varying_unknown_reals: ["Close", "Volume"]

  'kospi200': 
    time_idx: 'days_from_start'
    target: 'Close'
    group_ids: ['Symbol']
    static_categoricals: ['Symbol', 'Sector']
    static_reals: []
    time_varying_known_categoricals: ['day_of_week', 'day_of_month', 'week_of_year', 'month']
    variable_groups: {}
    time_varying_known_reals: ["days_from_start"]
    time_varying_unknown_categoricals: []
    # time_varying_unknown_reals: ["Close", "Volume"]
    time_varying_unknown_reals: ["Open", "High", "Low", "Close", "Volume", "Change"]

  'kospi200+AUDCHF': 
    time_idx: 'days_from_start'
    target: 'Close'
    group_ids: ['Symbol']
    static_categoricals: ['Symbol', 'Sector']
    static_reals: []
    time_varying_known_categoricals: ['day_of_week', 'day_of_month', 'week_of_year', 'month']
    variable_groups: {}
    time_varying_known_reals: ["days_from_start"]
    time_varying_unknown_categoricals: []
    time_varying_unknown_reals: ["Close", "Volume", "Change", "AUD_CHF_Close", "AUD_CHF_Change"]

  'kospi200+TI': 
    time_idx: 'days_from_start'
    target: 'Close'
    group_ids: ['Symbol']
    static_categoricals: ['Symbol', 'Sector']
    static_reals: []
    time_varying_known_categoricals: ['day_of_week', 'day_of_month', 'week_of_year', 'month']
    variable_groups: {}
    time_varying_known_reals: ["days_from_start"]
    time_varying_unknown_categoricals: []
    time_varying_unknown_reals: ['Close', 'Volume', 'Change', 'mc_mc', 'mc_mcdiff', 'mc_mcsig', 'pa_pa', 'pa_pad', 'pa_padi', 'pa_pau', 
                                'pa_paui', 'bb_bbm', 'bb_bbh', 'bb_bbl', 'bb_bbhi', 'bb_bbli', 'so_so', 'so_sosi', 'roc', 'obv', 'fi'] # 21 features

model:
  hidden_size: 160
  attention_head_size: 1 #1
  dropout: 0.3
  hidden_continuous_size: 8
  output_size: 3  # 7 quantiles by default
  log_interval: 10  # uncomment for learning rate finder and otherwise, e.g. to 10 for logging every 10 batches
  reduce_on_plateau_patience: 1000 # 1000
  alpha: 0.5 # (shape:time) ratio in DILATE
  weight: 0.01 # weight for directional and dilate quantile loss
  optimizer: 'ranger' # default: 'ranger'

experiment:
  epoch: 50 # 50
  batch_size: 512 # (64, 512)
  lr:
    vol: 0.01
    stock_idx: 0.01
    btc_krw: 0.01
    btc_usd: 0.01
    crypto: 0.01
    crypto_hourly: 0.01
    crypto_daily: 0.01
    sp500: 0.01
    kospi: 0.01
    kospi200: 0.01
    kospi200+AUDCHF: 0.01
    kospi200+TI: 0.01
  max_prediction_length: 5 #5
  max_encoder_length:
    vol: 252
    stock_idx: 252
    btc_krw: 252
    btc_usd: 252
    crypto: 252
    crypto_hourly: 252
    crypto_daily: 252
    sp500: 252
    kospi: 252
    kospi200: 252 # 252, 504
    kospi200+AUDCHF: 252
    kospi200+TI: 252
  symbol_boundary:
    '.SPX':
      'recession':
        - '2008.02.01'
        - '2009.02.01'
      'stable':
        - '2014.08.01'
        - '2015.08.01'
      'boom':
        - '2019.02.01'
        - '2020.02.01'
  train_boundary:
    vol: '2000'
    stock_idx: '2000'
    btc_krw: '2000'
    btc_usd: '2000' 
    crypto: '2000'
    crypto_hourly: '2000'
    crypto_daily: '2000'
    sp500: '2000'
    kospi: '2010'
    kospi200: '2010'
    kospi200+AUDCHF: '2010'
    kospi200+TI: '2010'
  valid_boundary: 
    vol: '2016'
    stock_idx: '2016'
    btc_krw: '2019'
    btc_usd: '2016' 
    crypto: '2016'
    crypto_hourly: '2019'
    crypto_daily: '2019'
    sp500: '2019'
    kospi: '2019'
    kospi200: '2019' # 2018, 2019
    kospi200+AUDCHF: '2019'
    kospi200+TI: '2019'
  test_boundary:
    vol: '2018'
    stock_idx: '2019'
    btc_krw: '2020'
    btc_usd: '2018'
    crypto: '2017'
    crypto_hourly: '2020'
    crypto_daily: '2020'
    sp500: '2020'
    kospi: '2020'
    kospi200: '2020'
    kospi200+AUDCHF: '2020'
    kospi200+TI: '2020'
  weights_summary: 'top'
  gradient_clip: 0.1 # 0.1
  limit_train_batches: 30 # 1.0
  
asset_root:
  '9': 
    'tft': '/data3/finance/assets/cjhan/tft_logs/'
    'deepar': '/data3/finance/assets/cjhan/deepar_logs/'

optuna_root:
  '9':
    'tft': '/data3/finance/assets/cjhan/tft_logs/optuna_test'
    'deepar': '/data3/finance/assets/cjhan/deepar_logs/optuna_test'

transfer_path:
  '9':
    'sp500': '/data3/finance/assets/cjhan/tft_logs/sp500/version_2/checkpoints/epoch=13.ckpt'
    'vol': '/data3/finance/assets/cjhan/tft_logs/vol/version_45/checkpoints/epoch=26.ckpt'
    'kospi': '/data3/finance/assets/cjhan/tft_logs/kospi/version_214/checkpoints/epoch=499.ckpt'

repeat_exp:
  '9': '/data3/finance/assets/cjhan/repeat_exp/'