data_root:
  '9': '/data3/finance'

dataset_setting:
  'volatility': 
    time_idx: 'days_from_start'
    target: 'log_vol'
    group_ids: ['Region', 'Symbol']
    static_categoricals: ['Region', 'Symbol']
    static_reals: []
    time_varying_known_categoricals: ["day_of_week", "day_of_month", "week_of_year", "month"]
    variable_groups: {}
    time_varying_known_reals: ["days_from_start"]
    time_varying_unknown_categoricals: []
    time_varying_unknown_reals: ["log_vol", "open_to_close"]
    
  'bitcoin': 
    time_idx: 'days_from_start'
    target: 'log_Close'
    group_ids: ['Symbol']
    static_categoricals: ['Symbol']
    static_reals: []
    time_varying_known_categoricals: ['day_of_week', 'day_of_month', 'week_of_year', 'month']
    variable_groups: {}
    time_varying_known_reals: ["days_from_start"]
    time_varying_unknown_categoricals: []
    time_varying_unknown_reals: ["log_Close", "Volume", "Change"]

model:
  hidden_size: 160
  attention_head_size: 1
  dropout: 0.3
  hidden_continuous_size: 8
  output_size: 3  # 7 quantiles by default
  log_interval: 10  # uncomment for learning rate finder and otherwise, e.g. to 10 for logging every 10 batches
  reduce_on_plateau_patience: 4

experiment:
  epoch: 100
  batch_size: 64
  lr: 0.1 # volatility: 0.01, bitcoin: 0.1
  max_prediction_length: 5
  max_encoder_length: 126 # volatility: 252, bitcoin: 126
  valid_boundary: '2019' # volatility: 2016, bitcoin: 2019
  test_boundary: '2020' # volatility: 2018, bitcoin: 2020
  weights_summary: 'top'
  gradient_clip: 0.1
  limit_train_batches: 1.0
  
asset_root:
  '9': '/data3/finance/assets/cjhan/tft_logs/'